### ISSUE TITLE
Dataset splits

### ISSUE THREAD

**Issue by ParthBibekar** [ml4bio/RiboDiffusion#1]
Hi,

Congrats on the great work. Can you make the data splits for train/test/val available? It would be nice to have a list of PDB ids and data from RNAcentral readily available. Thanks!

**Comment by liyu95** [comment]
Thank you for your interest. We will release the id once the work is officially published and online.

**Comment by ParthBibekar** [comment]
Hi, I notice that the paper is now published. Will the data splits be available on this repo?
